# dhound-agent configuration - https://knowledge.dhound.io/how-to-use-dhound

# New OUTBOUND connections from server to Internet (all private network addresses are excluded)
# Usually servers work with well-known trusted external resources (sending mail, payments, etc.). This event category shows all OUT established TCP connections and marks them as Warnings if server starts communication with untrusted location. This helps to define troyan, viruses injected on server that communicate with external malicious resources.

paths:
- /var/log/dhound/dhound-output-traffic-monitor*
- /var/log/syslog*
eventtimeformat: YYYY/MM/DD hh:mm:ss
events:
# TCP - success true
- sid: 10011
  regex: '(?P<eventTime>[12]\d{3}\/[0-9]{1,2}\/[0-9]{1,2}\d [0-9]{2}:[0-9]{2}:[0-9]{2}).*?tcp (?P<ip>.*?):(?P<port>\d+).*success:true(.+?pid:(?P<pid>[0-9]{1,})|)(.+?process:"(?P<process>.+?)"|)(.+?commandline:"(?P<commandline>.+?)"|)(.+?domains:(?P<domains>.*?)|).*timestamp:(?P<timestamp>\d{10}|)'

# TCP success false
- sid: 10012
  regex: '(?P<eventTime>[12]\d{3}\/[0-9]{1,2}\/[0-9]{1,2}\d [0-9]{2}:[0-9]{2}:[0-9]{2}).*?tcp (?P<ip>.*?):(?P<port>\d+).*success:false(.+?pid:(?P<pid>[0-9]{1,})|)(.+?process:"(?P<process>.+?)"|)(.+?commandline:"(?P<commandline>.+?)"|)(.+?domains:(?P<domains>.*?)|).*timestamp:(?P<timestamp>\d{10}|)'

# UDP success true
- sid: 10013
  regex: '(?P<eventTime>[12]\d{3}\/[0-9]{1,2}\/[0-9]{1,2}\d [0-9]{2}:[0-9]{2}:[0-9]{2}).*?udp (?P<ip>.*?):(?P<port>\d+).*success:true(.+?bytes:(?P<bytes>[0-9]{1,})|)(.+?pid:(?P<pid>[0-9]{1,})|)(.+?process:"(?P<process>.+?)"|).*timestamp:(?<timestamp>\d{10}|)'

# UDP success false
- sid: 10014
  regex: '(?P<eventTime>[12]\d{3}\/[0-9]{1,2}\/[0-9]{1,2}\d [0-9]{2}:[0-9]{2}:[0-9]{2}).*?udp (?P<ip>.*?):(?P<port>\d+).*success:false(.+?bytes:(?P<bytes>[0-9]{1,})|)(.+?pid:(?P<pid>[0-9]{1,})|)(.+?process:"(?P<process>.+?)"|).*timestamp:(?<timestamp>\d{10}|)'
