# dhound-agent configuration - https://knowledge.dhound.io/how-to-use-dhound

source: wineventlog
paths: 
- Microsoft-Windows-Windows Defender/Operational
events:
# updated windows defender signature database
- sid: 20501
  wineventids: [2000]
  regex: '<Data Name=.Current Signature Version.>(?P<version>.*?)<\/Data>'
  fields:
    ip: LOCAL

# virus detected by windows defender
- sid: 20502
  wineventids: [1006,1007,1008,1009,1116,1117,1118,1119]
  regex: '<Data Name=.Path.>(?P<file>.*?)<\/Data>|<Data Name=.Threat Name.>(?P<threat>.*?)<\/Data>'
  fields:
    ip: LOCAL
